### ISSUE TITLE
direct script vs python problem

### ISSUE THREAD

**Issue by dummerfranz** [lohriialo/indesign-scripting-python#11]
can someone explain to me why this script isnt working in python3?
In InDesign this script is working just fine...

```
import win32com.client
app = win32com.client.Dispatch('InDesign.Application')
app.activeDocument.dataMergeProperties.selectDataSource('C:/Users/test.csv')
```

console output:
Missing required parameter "DataSourceFile" for method "SelectDataSource".', None, 0, 0), None)

tried to apply but isnt working this way:

`test=app.activeDocument.dataMergeProperties.selectDataSource(DataSourceFile="C:/Users/g.overbeck/Desktop/python/tsptoolexp/flyer/input.csv")`

**Comment by lohriialo** [comment]
method names should be start with an upper-case as can be seen from [api_reference](https://raw.githubusercontent.com/lohriialo/indesign-scripting-python/master/api_reference/indesign_2021.py)

**Comment by dummerfranz** [comment]
Thanks for your reply.
